Данная проблема имеет непосредственное отношение к проблеме "DoS при вызове исключения". Суть заключается в том, что, если мы должны перевести некую сумму на другой контракт, имеет смысл сначала сохранить эту сумму в переменной, так как, если мы вычисляем эту сумму и сразу отсылаем результат вычислений без логирования, может случиться так, что на стороне рецепиента может произойти исключение и код не будет исполнен. В такой ситуации результат вычисления суммы для перевода не сохраниться и мы потеряем информацию. Для этого нужно сначала логировать результат и в отдельной функции отправлять эту самую сумму.